export const SUBMIT_ANSWER_REQUEST = "SUBMIT_ANSWER_REQUEST"
export const SUBMIT_ANSWER_SUCCESS = "SUBMIT_ANSWER_SUCCESS"
export const SUBMIT_ANSWER_FAIL = "SUBMIT_ANSWER_FAIL"

export const ANSWER_REQUEST = "ANSWER_REQUEST"
export const ANSWER_SUCCESS = "ANSWER_SUCCESS"
export const ANSWER_FAIL = "ANSWER_FAIL"
