export const SUBMIT_ASSIGNMENT_REQUEST = "SUBMIT_ASSIGNMENT_REQUEST"
export const SUBMIT_ASSIGNMENT_SUCCESS = "SUBMIT_ASSIGNMENT_SUCCESS"
export const SUBMIT_ASSIGNMENT_FAIL = "SUBMIT_ASSIGNMENT_FAIL"

export const ASSIGNMENT_REQUEST = "ASSIGNMENT_REQUEST"
export const ASSIGNMENT_SUCCESS = "ASSIGNMENT_SUCCESS"
export const ASSIGNMENT_FAIL = "ASSIGNMENT_FAIL"
